# version: '3.8'

services:
  ai-app:
    build: .
    container_name: leaderg_practice
    ports:
      - "8080:80"     # Nginx 埠
      - "5000:5000"   # Python Flask API 埠
    volumes:
      - .:/var/www/html

